Fix typos
macports/macports-guide pull request #16
Opened 2018-04-09 16:04 UTC by rex4539

2018-04-09 16:07 UTC, ryandesign reviewed
Thanks!

2018-04-09 16:07 UTC, ryandesign commented on guide/xml/portgroup-xcode.xml
> +          <para>Additional settings passed to the Xcode build tool during the
Possibly, this should have been "the `xcodebuild` tool".

2018-04-09 16:07 UTC, ryandesign commented on guide/xml/portgroup-xcode.xml
> +    <para>Portfiles using the Xcode PortGroup do not need to define the
The portgroup's name is capitalized "xcode" so I would not change this.

2018-04-09 16:17 UTC, rex4539 commented
Addressed comments :)

2018-04-09 16:18 UTC, raimue reviewed
Thank you for your contribution. The attention to detail is appreciated!

2018-04-09 16:18 UTC, raimue commented on guide/xml/portgroup-xcode.xml
> +          <para>Additional settings passed to the Xcode build tool during the
I guess this was actually supposed to read `xcodebuild`.

Although "passed to the `xcodebuild` tool" seems bulky, so I would shorten this phrase to "passed to `xcodebuild`".

2018-04-09 16:18 UTC, raimue commented on guide/xml/portgroup-xcode.xml
> +    <para>Portfiles using the Xcode PortGroup do not need to define the
Hm, this would be loaded with a `PortGroup xcode 1.0` statement, so the lower case version seems correct. For example, we also document the `github portgroup` in another section and not a `GitHub portgroup`.

Maybe it would better be phrased as "Portfiles using `PortGroup  xcode` do not need to..." here.

2018-04-09 16:28 UTC, rex4539 commented
Fixed!

2018-04-11 16:29 UTC, pmetzger requested changes

2018-04-11 16:29 UTC, pmetzger commented on guide/xml/portgroup-xcode.xml
> +          <para>Additional settings passed to xcodebuild tool during the
I think the "the" is still needed.

2018-04-11 16:29 UTC, pmetzger commented on guide/xml/portgroup-xcode.xml
> +          <para>Additional settings passed to xcodebuild tool during the
The "the" is still needed.

2018-04-11 16:29 UTC, pmetzger commented on guide/xml/portgroup-xcode.xml
> +          <para>Settings passed to xcodebuild tool when the +universal
The "the" is still needed.

2018-04-11 16:52 UTC, rex4539 commented
Added "the" in the 3 instances.

2018-04-11 19:02 UTC, merged

2018-04-11 19:03 UTC, pmetzger commented
Merged. Thank you for your help making the guide better!