Update installing.adoc
macports/macports-guide pull request #42
Opened 2020-12-12 13:49 UTC by JensTimmerman

you can't clone if you're not in the git repo yet

2020-12-12 16:35 UTC, neverpanic approved these changes

2020-12-12 16:35 UTC, neverpanic requested changes
Actually, the asciidoc version of the guide is currently still not used to actually build the contents of the website :/

Can you make the same change in the XML version?

2020-12-18 10:41 UTC, JensTimmerman commented
@neverpanic done

2020-12-18 14:32 UTC, neverpanic approved these changes
Thanks!

2020-12-18 14:32 UTC, merged